# Задачи по находению оптимального значения

## 1 задача (Задача о назначениях)
### Условие задачи:
Распределить работы таким образом, чтобы минимизировать
временные затраты на выполнение всех работ при условии, что
каждый из претендентов получит одну и только одну из работ.

In [1]:
import pandas as pd

x1 = [9,9,1,15,1,9,3,4,6,3]
x2 = [4,16,11,11,4,12,2,3,5,3]
x3 = [2,17,18,16,9,16,4,6,7,1]
x4 = [4,17,10,14,16,14,3,7,3,1]
x5 = [2,5,18,8,18,5,1,6,1,3]
x6 = [7,17,1,8,8,18,7,3,2,7]
x7 = [3,1,2,3,2,3,6,5,3,2]
x8 = [6,2,2,1,1,5,4,2,1,1]
x9 = [2,1,3,7,4,3,5,2,4,4]
x10 = [3,3,5,2,3,2,3,1,1,2]
x = [x1,x2,x3,x4,x5,x6,x7,x8,x9,x10]

columns = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
bases = ['Иванов', 'Петров', 'Сидоров', 'Копылов', 'Минин', 'Жаров', 'Власов', 'Демченко', 'Серегин', 'Панин'] 
table = pd.DataFrame(x, columns=columns) 
table.insert(0, 'Рабочий', bases) 
table.columns = pd.MultiIndex.from_arrays([ ['Рабочий'] + ['Работа, Время на выполнение']*10, [''] + columns ])
table

    Рабочий Работа, Время на выполнение
                                      1   2   3   4   5   6  7  8  9 10
0    Иванов                           9   9   1  15   1   9  3  4  6  3
1    Петров                           4  16  11  11   4  12  2  3  5  3
2   Сидоров                           2  17  18  16   9  16  4  6  7  1
3   Копылов                           4  17  10  14  16  14  3  7  3  1
4     Минин                           2   5  18   8  18   5  1  6  1  3
5     Жаров                           7  17   1   8   8  18  7  3  2  7
6    Власов                           3   1   2   3   2   3  6  5  3  2
7  Демченко                           6   2   2   1   1   5  4  2  1  1
8   Серегин                           2   1   3   7   4   3  5  2  4  4
9     Панин                           3   3   5   2   3   2  3  1  1  2

### Таблица 3.1

Индексы колонок: номера работ. </br>
Индексы строк: Работники. </br>
В ячейках записано за сколько тот или иной работник выполнит ту или иную работу.

### Функция длительности выполнения работ:
По условию, один работник может выполнять только одну работу. Значит нам нет необходимости разбивать одну работу по разным работникам,  Пусть x(i,j) - время выполнения работы работником.
w(i,j) - стоимость значения (w(i,j) ⍷ [0,1]

#### y = (i)∑(j)∑x(i,j)*w(i,j)

### Условия:
#### (i)∑w(i,j) = 1
#### (j)∑w(i,j) = 1

На основании этой функции напишем алгоритм поиска минимального времени:

In [2]:
from IPython.display import HTML


node0 = []
duration = 0
distr_list = []
worker = 0

def jobs(worker, node, duration):
    if len(node) == 10:
        distr_list.append([duration, node])
    for job in range(10):
        if (job not in node):
            jobs(worker+1, node+[job], duration + x[worker][job])
            
jobs(worker, node0, duration)
print(min(distr_list))
                        
                        
HTML(f"<p style='font-size:20px; color: rgb(200, 100, 150);'>Решение 1-й задачи: {min(distr_list)} часов - минимальное суммарное время, затраченное на проведение работ.</p>")

[14, [4, 6, 0, 9, 8, 2, 1, 3, 5, 7]]

### Вывод:
Иванов выполняет **работу 5**;</br>
Петров выполняет **работу 7**;</br>
Сидоров выполняет **работу 1**;</br>
Копылов выполняет **работу 10**;</br>
Минин выполняет **работу 9**;</br>
Жаров выполняет **работу 3**;</br>
Власов выполняет **работу 2**;</br>
Демченко выполняет **работу 4**;</br>
Серегин выполняет **работу 6**;</br>
Панин выполняет **работу 8**.</br>

## 2 задача (задача комивояжера)

### Условие задачи:
Дана транспортная сеть, которая соединяет 5 населенных пунктов в
некотором географическом районе. Данный район представлен в виде схемы,
формально представляющей собой ориентированный связный граф, состоящий из 5
вершин, которые связаны между собой в прямом и обратном направлении. Длина участка
автодороги между двумя соседними населенными пунктами, выраженная в км., равна
значению весовой функции для каждой дуги. Это значение указано рядом с изображением
соответствующей дуги в графе. Требуется найти такой полный замкнутый путь,
начинающийся в вершине с номером 1 и заканчивающийся в вершине с номером 5, чтобы
общая длина пути была минимальной.




![Карта путей](rover_passed.jpeg)

### Таблица

На основании данной "карты" составим таблицу отображающую расстояния между населенными пунктами:

In [4]:
my_map = [[0, 8, 9, 1, 3], 
          [5, 0, 7, 4, 8], 
          [6, 7, 0, 4, 2], 
          [4, 7, 1, 0, 4], 
          [1, 2, 5, 5, 0]] 

columns = ['V1', 'V2', 'V3', 'V4', 'V5'] 
bases = ['V1', 'V2', 'V3', 'V4', 'V5'] 
table2 = pd.DataFrame(my_map, columns=columns) 
table2.insert(0, 'Из', bases) 
table2.columns = pd.MultiIndex.from_arrays([ ['Из'] + ['В']*5, [''] + columns ])
table2

   Из  В
      V1 V2 V3 V4 V5
0  V1  0  8  9  1  3
1  V2  5  0  7  4  8
2  V3  6  7  0  4  2
3  V4  4  7  1  0  4
4  V5  1  2  5  5  0

Здесь мы видим расстояние из пункта Vi в пункт Vj, которое мы будем обозначать как v(i,j). Можно заметить, что v(i,j) и v(j,i) - разные по длине.
Так же мы обозначим x(i,j) как стоимость каждой их этих ячеек. x(i,j) ⍷ [0,1]. 1 - дорога участвует в пути, 0 - дорога не участвует в пути.

### Функция длины пути:
#### y = (i)∑(j)∑(v(i,j)*x(i,j)

### Условия:
#### (i)∑x(i,j) = 1
#### (j)∑x(i,j) = 1
#### i != j
#### (i)∑(j)∑x(i,j) = 5

На основании описанного выше напишу алгоритм поиска кратчайшего маршрута, проходящего через все населенные пункты ровно по одному разу.

In [14]:
current = 0
node = []
dist = 0
dist_l = []


def route(current, node, dist):
    node = node.copy()
    node.append(current)
    if len(node) == 5:
        dist_l.append([dist+my_map[current][0],list(map(lambda x: x+1, node))])
    if len(node) == 4:
        route(4, node, dist + my_map[current][4])
    for i in range(5):
        if (i not in node) and (i!=4):
            route(i, node, dist + my_map[current][i])
        
    return 
route(current, node, dist)

HTML(f"<p style='font-size:20px; color: rgb(200, 100, 150);'>Решение 2-й задачи: {min(dist_l)} км - кратчайший маршрут путешествия по всем населенным пунктам.</p>")

### Вывод:
Путешественник будет двигаться по маршруту:</br>
***V1 -> V2 -> V4 -> V3 -> V5***

![Пройденный путь](rover.jpeg)

## 3 задача (Задача о минимальном пути)

### Условие задачи:

Транспортному предприятию требуется перевезти груз из пункта 1 в пункт 14. На
рисунке показана сеть дорог и стоимость перевозки единицы груза между отдельными
пунктами. Определить маршрут доставки груза, которому соответствуют наименьшие
затраты.

![Карта путей 2](ways.png)

### Таблица

На основании данной "карты" составим таблицу отображающую затраты на перевозки между отдельными пунктами и связи между населенными пунктами (затраты a(i) указаны в третьем столбце):

In [6]:
my_map2 = [[1,2,18], 
           [1,3,19], 
           [1,4,17], 
           [2,4,13],
           [2,6,14],
           [3,6,15],
           [3,7,16],
           [4,7,17],
           [4,8,18],
           [5,6,21],
           [5,9,19],
           [6,9,22],
           [6,10,21],
           [7,10,23],
           [7,11,18],
           [8,7,21],
           [8,11,17],
           [9,12,32],
           [10,12,33],
           [10,13,37],
           [11,13,36],
           [10,14,41],
           [12,14,32],
           [13,14,31]]

columns = ['Из', 'В', 'Затраты'] 
table3 = pd.DataFrame(my_map2, columns=columns) 
table3

    Из   В  Затраты
0    1   2       18
1    1   3       19
2    1   4       17
3    2   4       13
4    2   6       14
5    3   6       15
6    3   7       16
7    4   7       17
8    4   8       18
9    5   6       21
10   5   9       19
11   6   9       22
12   6  10       21
13   7  10       23
14   7  11       18
15   8   7       21
16   8  11       17
17   9  12       32
18  10  12       33
19  10  13       37
20  11  13       36
21  10  14       41
22  12  14       32
23  13  14       31

Пусть Из[k] - i, В[k] - j, тогда Затраты[k] - v(i,j). Не все пунуты связаны между собой. 
Обозначим x(i,j) как стоимость каждой их этих ячеек. x(i,j) ⍷ [0,1]. 1 - дорога участвует в пути, 0 - дорога не участвует в пути.
s - начало пути
f - конец пути

### Функция длины пути:
#### y = (i)∑(j)∑(v(i,j)*x(i,j)

### Условия:
#### (i)∑(j)∑(x(i,j) < 8
#### (j)∑x(s,j) - (i)∑x(i,s) = 1
#### (j)∑x(t,j) - (i)∑x(i,t) = -1
#### (j)∑x(i,j) - (i)∑x(i,j) = 0, при j != s, i != t

На основании описанного выше напишу алгоритм поиска самого дешевого маршрута.

In [7]:
cur = 1
length = 0
len_list = []
node1 = []

def way(cur, len_, node1):
    node1 = node1.copy()
    node1.append(cur)
    if cur == 14:
        len_list.append([len_, node1])
        return
    else:
        options = [o for o in my_map2 if o[0]==cur]
        for _ in options:
            way(_[1], len_+_[2], node1)
        return
        
        
way(cur, length, node1)
HTML(f"<p style='font-size:20px; color: rgb(200, 100, 150);'>Решение 3-й задачи: {min(len_list)} денежных единиц - самый дешевый маршрут из V1 в V14.</p>")

### Вывод:

Наименее затратный путь из V1 в V14:</br>
***V1 -> V2 -> V6 -> V10 -> V14***

![Пройденный путь](ways_passed.png)

In [ ]:
remirina@bk.ru